### ISSUE TITLE
Headings to SSML

### ISSUE THREAD

**Issue by Fleker** [fabien88/ssmd#2]
Have a way where one can convert headings to SSML tags which may be a combination of emphasis and breaks.

```
# Heading 1
## Heading 2
```

```
<emphasis level="strong">Heading 1</emphasis>
<break time="100ms" />
<emphasis level="moderate">Heading 2</emphasis>
<break time="75ms" />
```

**Comment by fabien88** [comment]
Let me know if it fit your needs with this  :

### Headings

Heading tag adds emphasis and a small break by default, but you can configure it as you like :  

```
const ssml = ssmd("# My first heading 1", {
  headingLevels: {
    1: [
        { tag: "emphasis", value: 'strong' },
        { tag: "pause", value: '300ms' },
    ],

    // if we ommit key "2", it will uses default params for heading 2

    3: [
        { tag: "pause", value: '50ms' },
        { tag: "prosody", value: {rate: 'slow'} },
        { tag: "pause", value: '200ms' },
    ],
  }
});
```

You can use any tag and value referenced from [ssml-builder project](https://www.npmjs.com/package/ssml-builder/v/0.4.3)  

By default headings give :  
* \# Heading 1 -> strong emphasis and a 100ms pause after  
* \# Heading 2 -> moderate emphasis and a 75ms pause after  
* \# Heading 3 -> reduced emphasis and a 50ms pause after  

SSMD:

```
# Heading 1
## Heading 2
##Heading 2
### Heading 3
#### Heading 4 // Not handled by default 
```

SSML:

```html
<s><emphasis level='strong'>Heading 1</emphasis> <break time='300ms'/></s>
<s><emphasis level='moderate'>Heading 2</emphasis> <break time='75ms'/></s>
<s><emphasis level='moderate'>Heading 2</emphasis> <break time='75ms'/></s>
<s><break time='50ms'/> <prosody rate='slow'>Heading 3</prosody> <break time='200ms'/></s>
<s>#### Heading 4 // Not handled by default</s>
```

**Comment by Fleker** [comment]
This is great! I really like how it can be easily customized.
